import sys


def print_error_msg(msg):
    print(msg)
    sys.exit(1)
